title = "TOML for PicoM"

[serial]
com_port = "COM4"
com_baudrate = 921600
com_timeout_s = 0.1

[xmodem]
xmodem_retry = 5
xmodem_wait_s = 2.0
xmodem_package_size_bytes = 128

[debugging]
verbose = 1
ask_questions = 1

[terminal]
terminal_path = "C:\\Program Files (x86)\\teraterm5\\ttermpro.exe"
